import { useEffect,useMemo,useState } from 'react';
import { CalendarDaysIcon,CheckCircleIcon,ClockIcon,PlusIcon,XMarkIcon } from '@heroicons/react/24/outline';
import { toast } from 'sonner';import { supabase } from '../lib/supabaseClient';import { useUnidade } from '../contexts/UnidadeContext';import { applyUnidadeToPayload } from '../services/unidadesService';
import { hasSurgeryRoomConflict,isPreoperativeChecklistComplete,REQUIRED_PREOPERATIVE_CHECKS,SURGERY_FLOW,validateSurgery } from '../lib/surgeryRules';
import SearchableSelect from '../components/SearchableSelect';

const empty={paciente_id:'',cirurgiao_id:'',procedimento:'',sala:'',inicio_previsto:'',fim_previsto:'',lateralidade:'nao_aplicavel',risco_cirurgico:'',observacoes:''};
const checkLabels={identidade_confirmada:'Identidade do paciente',procedimento_confirmado:'Procedimento confirmado',sitio_confirmado:'Sítio/lateralidade',consentimento_confirmado:'Consentimento assinado',alergias_revisadas:'Alergias revisadas',risco_via_aerea_revisado:'Risco de via aérea',profilaxia_confirmada:'Profilaxia indicada',materiais_confirmados:'Materiais e implantes',contagem_confirmada:'Contagem de compressas/instrumentais',amostras_identificadas:'Amostras identificadas'};
const statusStyle={agendada:'bg-blue-100 text-blue-700',confirmada:'bg-cyan-100 text-cyan-700',em_preparo:'bg-amber-100 text-amber-700',em_cirurgia:'bg-red-100 text-red-700',recuperacao:'bg-violet-100 text-violet-700',concluida:'bg-emerald-100 text-emerald-700',cancelada:'bg-slate-100 text-slate-600'};

export default function CentroCirurgico(){const{unidadeAtualId}=useUnidade();const[loading,setLoading]=useState(true);const[cirurgias,setCirurgias]=useState([]);const[pacientes,setPacientes]=useState([]);const[prestadores,setPrestadores]=useState([]);const[form,setForm]=useState(empty);const[show,setShow]=useState(false);const[checkTarget,setCheckTarget]=useState(null);const[check,setCheck]=useState({});const[saving,setSaving]=useState(false);
const load=async()=>{setLoading(true);const day=new Date();day.setHours(0,0,0,0);const end=new Date(day);end.setDate(end.getDate()+7);const responses=await Promise.all([supabase.from('cirurgias').select('*,pacientes(nome),prestadores(nome),checklist_cirurgia_segura(*)').gte('inicio_previsto',day.toISOString()).lt('inicio_previsto',end.toISOString()).order('inicio_previsto'),supabase.from('pacientes').select('id,nome').order('nome'),supabase.from('prestadores').select('id,nome').eq('ativo',true).order('nome')]);const error=responses.find(r=>r.error)?.error;if(error)toast.error(error.code==='42P01'?'Execute a migração 20260826_centro_cirurgico.sql.':'Não foi possível carregar o centro cirúrgico.');else{setCirurgias(responses[0].data||[]);setPacientes(responses[1].data||[]);setPrestadores(responses[2].data||[])}setLoading(false)};useEffect(()=>{load()},[unidadeAtualId]);
const metrics=useMemo(()=>({today:cirurgias.filter(i=>new Date(i.inicio_previsto).toDateString()===new Date().toDateString()).length,room:cirurgias.filter(i=>i.status==='em_cirurgia').length,recovery:cirurgias.filter(i=>i.status==='recuperacao').length,pending:cirurgias.filter(i=>i.status==='em_preparo'&&!isPreoperativeChecklistComplete(Array.isArray(i.checklist_cirurgia_segura)?i.checklist_cirurgia_segura[0]:i.checklist_cirurgia_segura)).length}),[cirurgias]);
const create=async e=>{e.preventDefault();const error=validateSurgery(form);if(error)return toast.error(error);if(hasSurgeryRoomConflict(form,cirurgias))return toast.error('Já existe cirurgia nesta sala durante o período informado.');setSaving(true);const{error:dbError}=await supabase.from('cirurgias').insert(applyUnidadeToPayload({...form,paciente_id:Number(form.paciente_id),cirurgiao_id:form.cirurgiao_id?Number(form.cirurgiao_id):null,fim_previsto:form.fim_previsto||null},unidadeAtualId));setSaving(false);if(dbError)return toast.error(dbError.message);toast.success('Cirurgia adicionada ao mapa.');setShow(false);setForm(empty);load()};
const advance=async item=>{const next=SURGERY_FLOW[item.status]?.next;if(next==='em_cirurgia'&&!isPreoperativeChecklistComplete(Array.isArray(item.checklist_cirurgia_segura)?item.checklist_cirurgia_segura[0]:item.checklist_cirurgia_segura)){setCheckTarget(item);return}const{error}=await supabase.rpc('avancar_cirurgia',{p_cirurgia_id:item.id,p_status:next});if(error)return toast.error(error.message);toast.success(`Cirurgia: ${SURGERY_FLOW[next].label}.`);load()};
const saveCheck=async()=>{if(!isPreoperativeChecklistComplete(check))return toast.error('Conclua todos os itens obrigatórios antes da entrada em sala.');setSaving(true);const{error}=await supabase.from('checklist_cirurgia_segura').upsert(applyUnidadeToPayload({...check,cirurgia_id:checkTarget.id,confirmado_em:new Date().toISOString()},unidadeAtualId),{onConflict:'cirurgia_id'});if(error){setSaving(false);return toast.error(error.message)}const response=await supabase.rpc('avancar_cirurgia',{p_cirurgia_id:checkTarget.id,p_status:'em_cirurgia'});setSaving(false);if(response.error)return toast.error(response.error.message);toast.success('Checklist confirmado e cirurgia iniciada.');setCheckTarget(null);setCheck({});load()};
if(loading)return <div className="flex h-72 items-center justify-center"><div className="h-12 w-12 animate-spin rounded-full border-b-2 border-rose-600"/></div>;
return <div className="min-h-screen bg-slate-50 p-4 dark:bg-gray-950 md:p-6"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><span className="text-xs font-bold uppercase tracking-widest text-rose-600">Assistência · Bloco operatório</span><h1 className="text-2xl font-bold dark:text-white">Centro Cirúrgico</h1><p className="text-sm text-slate-500">Mapa cirúrgico, fluxo de sala e checklist de cirurgia segura.</p></div><button onClick={()=>setShow(true)} className="flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-3 text-sm font-semibold text-white"><PlusIcon className="h-5 w-5"/>Agendar cirurgia</button></header>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Cirurgias hoje" value={metrics.today}/><Metric label="Em cirurgia" value={metrics.room} color="text-red-600"/><Metric label="Em recuperação" value={metrics.recovery} color="text-violet-600"/><Metric label="Checklist pendente" value={metrics.pending} color="text-amber-600"/></section>
<section className="overflow-hidden rounded-2xl border bg-white dark:border-gray-800 dark:bg-gray-900"><div className="border-b p-5 dark:border-gray-800"><h2 className="flex items-center gap-2 font-bold dark:text-white"><CalendarDaysIcon className="h-5 w-5 text-rose-600"/>Mapa dos próximos 7 dias</h2></div><div className="divide-y dark:divide-gray-800">{cirurgias.map(item=><article key={item.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_1.6fr_1fr_auto] lg:items-center"><div><strong className="block dark:text-white">{new Date(item.inicio_previsto).toLocaleDateString('pt-BR')}</strong><span className="flex items-center gap-1 text-sm text-slate-500"><ClockIcon className="h-4 w-4"/>{new Date(item.inicio_previsto).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · {item.sala}</span></div><div><h3 className="font-semibold dark:text-gray-200">{item.pacientes?.nome} · {item.procedimento}</h3><p className="text-xs text-slate-500">Cirurgião: {item.prestadores?.nome||'Não definido'} · {item.lateralidade}</p></div><span className={`w-fit rounded-full px-2 py-1 text-xs font-semibold ${statusStyle[item.status]}`}>{SURGERY_FLOW[item.status]?.label}</span>{SURGERY_FLOW[item.status]?.next&&<button onClick={()=>advance(item)} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{SURGERY_FLOW[SURGERY_FLOW[item.status].next].label}</button>}</article>)}{!cirurgias.length&&<p className="p-12 text-center text-sm text-slate-500">Nenhuma cirurgia no período.</p>}</div></section></div>
{show&&<Modal title="Agendar cirurgia" close={()=>setShow(false)}><form onSubmit={create} className="grid gap-4 md:grid-cols-2"><SearchableSelect label="Paciente" value={form.paciente_id} onChange={v=>setForm({...form,paciente_id:v})} options={pacientes} required/><Select label="Cirurgião" value={form.cirurgiao_id} set={v=>setForm({...form,cirurgiao_id:v})} options={prestadores} optional/><Input label="Procedimento" value={form.procedimento} set={v=>setForm({...form,procedimento:v})}/><Input label="Sala" value={form.sala} set={v=>setForm({...form,sala:v})}/><Input label="Início previsto" type="datetime-local" value={form.inicio_previsto} set={v=>setForm({...form,inicio_previsto:v})}/><Input label="Fim previsto" type="datetime-local" value={form.fim_previsto} set={v=>setForm({...form,fim_previsto:v})} optional/><label className="text-sm dark:text-gray-200">Lateralidade<select value={form.lateralidade} onChange={e=>setForm({...form,lateralidade:e.target.value})} className="input"><option value="nao_aplicavel">Não aplicável</option><option value="direita">Direita</option><option value="esquerda">Esquerda</option><option value="bilateral">Bilateral</option></select></label><Input label="Risco cirúrgico" value={form.risco_cirurgico} set={v=>setForm({...form,risco_cirurgico:v})} optional/><div className="md:col-span-2"><Submit saving={saving}/></div></form></Modal>}
{checkTarget&&<Modal title="Checklist pré-operatório" close={()=>setCheckTarget(null)}><p className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{checkTarget.pacientes?.nome} · {checkTarget.procedimento}</p><div className="space-y-2">{Object.entries(checkLabels).map(([field,label])=><label key={field} className={`flex items-center gap-3 rounded-xl border p-3 text-sm ${REQUIRED_PREOPERATIVE_CHECKS.includes(field)?'border-rose-200':'border-slate-200'}`}><input type="checkbox" checked={Boolean(check[field])} onChange={e=>setCheck({...check,[field]:e.target.checked})}/><span>{label}{REQUIRED_PREOPERATIVE_CHECKS.includes(field)&&<strong className="text-rose-600"> *</strong>}</span></label>)}</div><button onClick={saveCheck} disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-rose-600 p-3 font-semibold text-white"><CheckCircleIcon className="h-5 w-5"/>Confirmar e iniciar cirurgia</button></Modal>}</div>}
function Metric({label,value,color='text-rose-600'}){return <article className="rounded-2xl border bg-white p-5 dark:border-gray-800 dark:bg-gray-900"><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${color}`}>{value}</p></article>};function Modal({title,close,children}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-4"><div className="mx-auto my-8 max-w-2xl rounded-3xl bg-white p-6 dark:bg-gray-900"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold dark:text-white">{title}</h2><button onClick={close}><XMarkIcon className="h-6 w-6"/></button></div>{children}</div></div>};function Input({label,value,set,type='text',optional}){return <label className="text-sm dark:text-gray-200">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} required={!optional} className="input"/></label>};function Select({label,value,set,options,optional}){return <label className="text-sm dark:text-gray-200">{label}<select value={value} onChange={e=>set(e.target.value)} required={!optional} className="input"><option value="">Selecione</option>{options.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></label>};function Submit({saving}){return <button disabled={saving} className="w-full rounded-xl bg-rose-600 p-3 font-semibold text-white">{saving?'Salvando...':'Agendar cirurgia'}</button>}
