import { useEffect, useState } from 'react';
import { PlusIcon, TrashIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { toast } from 'sonner';
import { supabase } from '../lib/supabaseClient';
const emptyPlan={nome:'',codigo:'',acomodacao:'ambulatorial',coparticipacao:false,percentual_coparticipacao:0,ativo:true};
export default function PlanosConvenioModal({convenio,onClose}) {
 const [plans,setPlans]=useState([]),[form,setForm]=useState(emptyPlan),[loading,setLoading]=useState(true);
 const load=async()=>{const {data,error}=await supabase.from('planos_convenio').select('*').eq('convenio_id',convenio.id).order('nome');if(error)toast.error(error.code==='42P01'?'Execute a migração 20260827_planos_fluxo_senhas.sql.':error.message);setPlans(data||[]);setLoading(false);};
 useEffect(()=>{load();},[convenio.id]);
 const save=async e=>{e.preventDefault();if(!form.nome.trim())return toast.error('Informe o nome do plano.');const {error}=await supabase.from('planos_convenio').insert({...form,nome:form.nome.trim(),codigo:form.codigo.trim()||null,convenio_id:convenio.id});if(error)return toast.error(error.message);toast.success('Plano incluído.');setForm(emptyPlan);load();};
 const remove=async id=>{if(!confirm('Excluir este plano?'))return;const {error}=await supabase.from('planos_convenio').delete().eq('id',id);if(error)return toast.error(error.message);toast.success('Plano excluído.');load();};
 return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white p-6 shadow-2xl dark:bg-gray-800"><header className="mb-5 flex items-start justify-between"><div><h2 className="text-xl font-bold dark:text-white">Planos de {convenio.nome_fantasia||convenio.razao_social}</h2><p className="text-sm text-gray-500">Produtos comercializados, acomodação e coparticipação.</p></div><button onClick={onClose}><XMarkIcon className="h-6 w-6"/></button></header>
 <form onSubmit={save} className="grid gap-3 rounded-xl bg-gray-50 p-4 dark:bg-gray-900 md:grid-cols-6"><input className="input md:col-span-2" placeholder="Nome do plano *" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/><input className="input" placeholder="Código" value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/><select className="input" value={form.acomodacao} onChange={e=>setForm({...form,acomodacao:e.target.value})}><option value="ambulatorial">Ambulatorial</option><option value="enfermaria">Enfermaria</option><option value="apartamento">Apartamento</option></select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={form.coparticipacao} onChange={e=>setForm({...form,coparticipacao:e.target.checked})}/>Coparticipação</label><button className="flex items-center justify-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white"><PlusIcon className="h-4 w-4"/>Incluir</button></form>
 <div className="mt-4 max-h-80 divide-y overflow-y-auto rounded-xl border dark:border-gray-700">{loading?<p className="p-6 text-center text-sm">Carregando...</p>:plans.map(plan=><div key={plan.id} className="flex items-center justify-between p-4"><div><strong className="text-sm dark:text-white">{plan.nome}</strong><p className="text-xs text-gray-500">{plan.codigo||'Sem código'} · {plan.acomodacao} · {plan.coparticipacao?`${plan.percentual_coparticipacao}% de coparticipação`:'Sem coparticipação'}</p></div><button onClick={()=>remove(plan.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><TrashIcon className="h-4 w-4"/></button></div>)}{!loading&&!plans.length&&<p className="p-8 text-center text-sm text-gray-500">Nenhum plano cadastrado.</p>}</div></div></div>;
}
