-- Marco 1: Core institucional, RBAC, estrutura hospitalar, auditoria e Storage privado.
begin;
create extension if not exists pgcrypto;

create table public.empresas(id uuid primary key default gen_random_uuid(),nome text not null,cnpj text,ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid());
create unique index empresas_cnpj_uidx on public.empresas(cnpj) where cnpj is not null and ativo;
create table public.unidades(id uuid primary key default gen_random_uuid(),empresa_id uuid not null references public.empresas(id),nome text not null,cnpj text,cnes text,timezone text not null default 'America/Sao_Paulo',ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid(),unique(empresa_id,nome));
create table public.usuarios(id uuid primary key references auth.users(id),nome text not null,bloqueado boolean not null default false,ativo boolean not null default true,ultimo_acesso_em timestamptz,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid());
create table public.perfis(id uuid primary key default gen_random_uuid(),empresa_id uuid references public.empresas(id),nome text not null,escopo text not null check(escopo in ('SISTEMA','EMPRESA','UNIDADE')),sistema boolean not null default false,ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid());
create table public.permissoes(id uuid primary key default gen_random_uuid(),codigo text not null unique,descricao text not null,modulo text not null,created_at timestamptz not null default now());
create table public.perfis_permissoes(perfil_id uuid not null references public.perfis(id),permissao_id uuid not null references public.permissoes(id),created_at timestamptz not null default now(),created_by uuid default auth.uid(),primary key(perfil_id,permissao_id));
create table public.usuarios_empresas(usuario_id uuid not null references public.usuarios(id),empresa_id uuid not null references public.empresas(id),perfil_id uuid not null references public.perfis(id),ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),primary key(usuario_id,empresa_id));
create table public.usuarios_unidades(usuario_id uuid not null references public.usuarios(id),empresa_id uuid not null references public.empresas(id),unidade_id uuid not null references public.unidades(id),perfil_id uuid not null references public.perfis(id),ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),primary key(usuario_id,unidade_id));

create table public.setores(id uuid primary key default gen_random_uuid(),empresa_id uuid not null references public.empresas(id),unidade_id uuid not null references public.unidades(id),nome text not null,tipo text not null,ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid(),unique(unidade_id,nome));
create table public.ambientes(id uuid primary key default gen_random_uuid(),empresa_id uuid not null references public.empresas(id),unidade_id uuid not null references public.unidades(id),setor_id uuid not null references public.setores(id),nome text not null,tipo text not null check(tipo in ('CONSULTORIO','SALA','QUARTO','BOX','POSTO','OUTRO')),ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid(),unique(unidade_id,setor_id,nome));
create table public.leitos(id uuid primary key default gen_random_uuid(),empresa_id uuid not null references public.empresas(id),unidade_id uuid not null references public.unidades(id),setor_id uuid not null references public.setores(id),ambiente_id uuid references public.ambientes(id),codigo text not null,tipo text not null,status text not null default 'LIVRE' check(status in ('LIVRE','RESERVADO','OCUPADO','HIGIENIZACAO','MANUTENCAO','BLOQUEADO')),ativo boolean not null default true,created_at timestamptz not null default now(),created_by uuid default auth.uid(),updated_at timestamptz not null default now(),updated_by uuid default auth.uid(),unique(unidade_id,codigo));

create table public.auditoria_eventos(id uuid primary key default gen_random_uuid(),empresa_id uuid,unidade_id uuid,usuario_id uuid,correlacao_id uuid not null default gen_random_uuid(),operacao text not null,entidade text not null,registro_id text,origem text not null default 'WEB',alteracoes jsonb,ip inet,user_agent text,created_at timestamptz not null default now());
create table public.acessos(id uuid primary key default gen_random_uuid(),usuario_id uuid,empresa_id uuid,unidade_id uuid,evento text not null check(evento in ('LOGIN','LOGOUT','FALHA','BLOQUEIO')),correlacao_id uuid not null default gen_random_uuid(),ip inet,user_agent text,created_at timestamptz not null default now());
create table public.arquivos(id uuid primary key default gen_random_uuid(),empresa_id uuid not null references public.empresas(id),unidade_id uuid references public.unidades(id),bucket text not null,objeto text not null,mime_type text not null,tamanho_bytes bigint not null check(tamanho_bytes>0),versao integer not null default 1,entidade text,registro_id uuid,created_at timestamptz not null default now(),created_by uuid not null default auth.uid(),cancelado_em timestamptz,unique(bucket,objeto,versao));

-- SECURITY DEFINER é necessário para avaliar vínculos sob RLS; search_path fixo, PUBLIC revogado e usuário bloqueado validado.
create function public.usuario_ativo() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from usuarios where id=auth.uid() and ativo and not bloqueado)$$;
create function public.tem_empresa(p_empresa uuid) returns boolean language sql stable security definer set search_path=public as $$select public.usuario_ativo() and exists(select 1 from usuarios_empresas where usuario_id=auth.uid() and empresa_id=p_empresa and ativo)$$;
create function public.tem_unidade(p_unidade uuid) returns boolean language sql stable security definer set search_path=public as $$select public.usuario_ativo() and exists(select 1 from usuarios_unidades where usuario_id=auth.uid() and unidade_id=p_unidade and ativo)$$;
create function public.tem_permissao(p_codigo text,p_empresa uuid default null,p_unidade uuid default null) returns boolean language sql stable security definer set search_path=public as $$select public.usuario_ativo() and exists(select 1 from usuarios_unidades uu join perfis_permissoes pp on pp.perfil_id=uu.perfil_id join permissoes p on p.id=pp.permissao_id where uu.usuario_id=auth.uid() and uu.ativo and (p_unidade is null or uu.unidade_id=p_unidade) and (p_empresa is null or uu.empresa_id=p_empresa) and p.codigo=p_codigo union all select 1 from usuarios_empresas ue join perfis_permissoes pp on pp.perfil_id=ue.perfil_id join permissoes p on p.id=pp.permissao_id where ue.usuario_id=auth.uid() and ue.ativo and (p_empresa is null or ue.empresa_id=p_empresa) and p.codigo=p_codigo)$$;
revoke all on function public.usuario_ativo(),public.tem_empresa(uuid),public.tem_unidade(uuid),public.tem_permissao(text,uuid,uuid) from public;
grant execute on function public.usuario_ativo(),public.tem_empresa(uuid),public.tem_unidade(uuid),public.tem_permissao(text,uuid,uuid) to authenticated;

insert into public.permissoes(codigo,descricao,modulo) values
('sistema.administrar','Administrar o sistema','core'),('empresa.administrar','Administrar empresa','core'),('unidade.administrar','Administrar unidade','estrutura'),('estrutura.gerenciar','Gerenciar estrutura hospitalar','estrutura'),('usuarios.gerenciar','Gerenciar usuários e vínculos','usuarios'),('pacientes.visualizar','Visualizar pacientes','pacientes'),('pacientes.criar','Criar pacientes','pacientes'),('pacientes.editar','Editar pacientes','pacientes'),('atendimentos.abrir','Abrir atendimento','atendimentos'),('atendimentos.transferir','Transferir atendimento','atendimentos'),('atendimentos.alta','Registrar alta','atendimentos'),('triagem.registrar','Registrar triagem','triagem'),('prontuario.visualizar','Visualizar prontuário','prontuario'),('prontuario.evoluir','Evoluir prontuário','prontuario'),('prescricao.criar','Criar prescrição','prescricao'),('prescricao.suspender','Suspender prescrição','prescricao'),('faturamento.visualizar','Visualizar faturamento','faturamento'),('faturamento.fechar','Fechar faturamento','faturamento'),('auditoria.visualizar','Visualizar auditoria','auditoria');

-- Bootstrap de uso único: exige JWT autenticado e banco institucional vazio.
create function public.bootstrap_primeiro_admin(p_nome text,p_empresa text,p_unidade text) returns public.usuarios language plpgsql security definer set search_path=public as $$
declare v_empresa uuid;v_unidade uuid;v_perfil uuid;v_usuario public.usuarios;
begin
  if auth.uid() is null then raise exception 'Autenticação obrigatória'; end if;
  perform pg_advisory_xact_lock(hashtext('nexo.bootstrap'));
  if exists(select 1 from usuarios) or exists(select 1 from empresas) then raise exception 'Bootstrap já realizado'; end if;
  insert into empresas(nome,created_by) values(trim(p_empresa),auth.uid()) returning id into v_empresa;
  insert into unidades(empresa_id,nome,created_by) values(v_empresa,trim(p_unidade),auth.uid()) returning id into v_unidade;
  insert into usuarios(id,nome,created_by) values(auth.uid(),trim(p_nome),auth.uid()) returning * into v_usuario;
  insert into perfis(empresa_id,nome,escopo,sistema,created_by) values(null,'Administrador do sistema','SISTEMA',true,auth.uid()) returning id into v_perfil;
  insert into perfis_permissoes(perfil_id,permissao_id,created_by) select v_perfil,id,auth.uid() from permissoes;
  insert into usuarios_empresas(usuario_id,empresa_id,perfil_id,created_by) values(auth.uid(),v_empresa,v_perfil,auth.uid());
  insert into usuarios_unidades(usuario_id,empresa_id,unidade_id,perfil_id,created_by) values(auth.uid(),v_empresa,v_unidade,v_perfil,auth.uid());
  insert into auditoria_eventos(empresa_id,unidade_id,usuario_id,operacao,entidade,registro_id,origem) values(v_empresa,v_unidade,auth.uid(),'BOOTSTRAP','usuarios',auth.uid()::text,'WEB');
  return v_usuario;
end $$;
revoke all on function public.bootstrap_primeiro_admin(text,text,text) from public;
grant execute on function public.bootstrap_primeiro_admin(text,text,text) to authenticated;

alter table public.empresas enable row level security;alter table public.unidades enable row level security;alter table public.usuarios enable row level security;alter table public.perfis enable row level security;alter table public.permissoes enable row level security;alter table public.perfis_permissoes enable row level security;alter table public.usuarios_empresas enable row level security;alter table public.usuarios_unidades enable row level security;alter table public.setores enable row level security;alter table public.ambientes enable row level security;alter table public.leitos enable row level security;alter table public.auditoria_eventos enable row level security;alter table public.acessos enable row level security;alter table public.arquivos enable row level security;
create policy empresas_select on public.empresas for select to authenticated using(public.tem_empresa(id));create policy empresas_manage on public.empresas for all to authenticated using(public.tem_permissao('empresa.administrar',id,null)) with check(public.tem_permissao('empresa.administrar',id,null));
create policy unidades_select on public.unidades for select to authenticated using(public.tem_unidade(id));create policy unidades_manage on public.unidades for all to authenticated using(public.tem_permissao('unidade.administrar',empresa_id,id)) with check(public.tem_permissao('unidade.administrar',empresa_id,id));
create policy usuarios_self on public.usuarios for select to authenticated using(id=auth.uid());
create policy permissoes_authenticated on public.permissoes for select to authenticated using(public.usuario_ativo());
create policy setores_select on public.setores for select to authenticated using(public.tem_unidade(unidade_id));create policy setores_manage on public.setores for all to authenticated using(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id)) with check(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id));
create policy ambientes_select on public.ambientes for select to authenticated using(public.tem_unidade(unidade_id));create policy ambientes_manage on public.ambientes for all to authenticated using(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id)) with check(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id));
create policy leitos_select on public.leitos for select to authenticated using(public.tem_unidade(unidade_id));create policy leitos_manage on public.leitos for all to authenticated using(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id)) with check(public.tem_permissao('estrutura.gerenciar',empresa_id,unidade_id));
create policy vinculos_empresa_self on public.usuarios_empresas for select to authenticated using(usuario_id=auth.uid());create policy vinculos_unidade_self on public.usuarios_unidades for select to authenticated using(usuario_id=auth.uid());
create policy perfis_scope on public.perfis for select to authenticated using(empresa_id is null or public.tem_empresa(empresa_id));create policy perfis_permissoes_scope on public.perfis_permissoes for select to authenticated using(exists(select 1 from perfis p where p.id=perfil_id and (p.empresa_id is null or public.tem_empresa(p.empresa_id))));
create policy auditoria_select on public.auditoria_eventos for select to authenticated using(public.tem_permissao('auditoria.visualizar',empresa_id,unidade_id));create policy arquivos_select on public.arquivos for select to authenticated using(public.tem_empresa(empresa_id) and (unidade_id is null or public.tem_unidade(unidade_id)));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('documentos-pacientes','documentos-pacientes',false,10485760,array['application/pdf','image/jpeg','image/png']),('prontuarios','prontuarios',false,10485760,array['application/pdf']),('documentos-medicos','documentos-medicos',false,10485760,array['application/pdf']),('resultados-laudos','resultados-laudos',false,52428800,array['application/pdf','image/jpeg','image/png']),('anexos-autorizacao','anexos-autorizacao',false,10485760,array['application/pdf','image/jpeg','image/png']),('anexos-faturamento','anexos-faturamento',false,20971520,array['application/pdf','application/xml','application/zip']),('glosas-recursos','glosas-recursos',false,20971520,array['application/pdf','image/jpeg','image/png']) on conflict(id) do update set public=false;
-- Objetos começam por empresa_id/unidade_id; emissão de URL assinada ocorre somente no servidor após checagem RBAC.
create policy storage_clinico_select on storage.objects for select to authenticated using(bucket_id in ('documentos-pacientes','prontuarios','documentos-medicos','resultados-laudos','anexos-autorizacao','anexos-faturamento','glosas-recursos') and public.tem_empresa((storage.foldername(name))[1]::uuid) and public.tem_unidade((storage.foldername(name))[2]::uuid));

grant select on public.empresas,public.unidades,public.usuarios,public.perfis,public.permissoes,public.perfis_permissoes,public.usuarios_empresas,public.usuarios_unidades,public.setores,public.ambientes,public.leitos,public.auditoria_eventos,public.acessos,public.arquivos to authenticated;
grant insert,update on public.empresas,public.unidades,public.setores,public.ambientes,public.leitos to authenticated;
commit;
