import { useEffect,useState } from 'react';
import { loadClinicalSupport,registerAttendanceDiagnosis,registerCareRequest } from '../lib/hisApi';

const emptyDiagnosis={cid10:'',descricao:'',tipo:'PRINCIPAL',situacao:'PROVISORIO',infectocontagioso:false};
const emptyRequest={tipo:'LABORATORIO',descricao:'',codigo_tuss:'',quantidade:1,indicacao:'',cid10:'',urgencia:'ROTINA',requer_autorizacao:false,senha:'',valor_unitario:0};
export default function ClinicalSupportPanels({attendanceId,version=0}){
  const[data,setData]=useState({diagnosticos:[],solicitacoes:[],documentos:[],status:[],conta:[]}),[tab,setTab]=useState('diagnosticos'),[diagnosis,setDiagnosis]=useState(emptyDiagnosis),[request,setRequest]=useState(emptyRequest),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  async function reload(){if(!attendanceId)return;try{setData(await loadClinicalSupport(attendanceId));setError('');}catch(e){setError(e.message);}}
  useEffect(()=>{reload();},[attendanceId,version]);
  async function saveDiagnosis(e){e.preventDefault();setSaving(true);try{await registerAttendanceDiagnosis(attendanceId,diagnosis);setDiagnosis(emptyDiagnosis);await reload();}catch(err){setError(err.message);}finally{setSaving(false);}}
  async function saveRequest(e){e.preventDefault();setSaving(true);try{await registerCareRequest(attendanceId,request);setRequest(emptyRequest);await reload();}catch(err){setError(err.message);}finally{setSaving(false);}}
  const tabs=[['diagnosticos','Diagnósticos',data.diagnosticos.length],['solicitacoes','Pedidos',data.solicitacoes.length],['documentos','Documentos',data.documentos.length],['conta','Conta',data.conta.length],['timeline','Linha do tempo',data.status.length]];
  return <section className="clinical-support"><nav>{tabs.map(([id,label,count])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}<b>{count}</b></button>)}</nav>{error&&<p className="module-error">{error}</p>}
    {tab==='diagnosticos'&&<div className="support-grid"><form onSubmit={saveDiagnosis}><h4>Novo diagnóstico</h4><input required placeholder="CID-10" value={diagnosis.cid10} onChange={e=>setDiagnosis({...diagnosis,cid10:e.target.value.toUpperCase()})}/><input required placeholder="Descrição clínica" value={diagnosis.descricao} onChange={e=>setDiagnosis({...diagnosis,descricao:e.target.value})}/><select value={diagnosis.tipo} onChange={e=>setDiagnosis({...diagnosis,tipo:e.target.value})}><option value="PRINCIPAL">Principal</option><option value="SECUNDARIO">Secundário</option></select><select value={diagnosis.situacao} onChange={e=>setDiagnosis({...diagnosis,situacao:e.target.value})}><option value="PROVISORIO">Provisório</option><option value="CONFIRMADO">Confirmado</option></select><label><input type="checkbox" checked={diagnosis.infectocontagioso} onChange={e=>setDiagnosis({...diagnosis,infectocontagioso:e.target.checked})}/> Alerta infectocontagioso</label><button disabled={saving} className="primary">Adicionar diagnóstico</button></form><RecordList empty="Nenhum diagnóstico registrado.">{data.diagnosticos.map(x=><article key={x.id}><strong>{x.cid10} · {x.descricao}</strong><small>{x.tipo} · {x.situacao}{x.infectocontagioso?' · ALERTA INFECTOCONTAGIOSO':''}</small></article>)}</RecordList></div>}
    {tab==='solicitacoes'&&<div className="support-grid"><form onSubmit={saveRequest}><h4>Novo pedido</h4><select value={request.tipo} onChange={e=>setRequest({...request,tipo:e.target.value})}>{['LABORATORIO','IMAGEM','PATOLOGIA','PROCEDIMENTO','CIRURGIA','TERAPIA','HEMOTERAPIA','INTERCONSULTA'].map(x=><option key={x}>{x}</option>)}</select><input required placeholder="Procedimento / exame" value={request.descricao} onChange={e=>setRequest({...request,descricao:e.target.value})}/><input placeholder="Código TUSS" value={request.codigo_tuss} onChange={e=>setRequest({...request,codigo_tuss:e.target.value})}/><input placeholder="Indicação clínica" value={request.indicacao} onChange={e=>setRequest({...request,indicacao:e.target.value})}/><input placeholder="CID relacionado" value={request.cid10} onChange={e=>setRequest({...request,cid10:e.target.value.toUpperCase()})}/><select value={request.urgencia} onChange={e=>setRequest({...request,urgencia:e.target.value})}><option>ROTINA</option><option>URGENTE</option><option>EMERGENCIA</option></select><label><input type="checkbox" checked={request.requer_autorizacao} onChange={e=>setRequest({...request,requer_autorizacao:e.target.checked})}/> Requer autorização</label>{request.requer_autorizacao&&<input placeholder="Senha da autorização" value={request.senha} onChange={e=>setRequest({...request,senha:e.target.value})}/>}<button disabled={saving} className="primary">Solicitar e lançar na conta</button></form><RecordList empty="Nenhum pedido registrado.">{data.solicitacoes.map(x=><article key={x.id}><strong>{x.tipo} · {x.descricao}</strong><small>{x.codigo_tuss||'Sem TUSS'} · {x.urgencia} · {x.status}</small></article>)}</RecordList></div>}
    {tab==='documentos'&&<RecordList empty="Nenhum documento emitido.">{data.documentos.map(x=><article key={x.id}><strong>{x.tipo} · {x.dias_afastamento?`${x.dias_afastamento} dia(s)`:'sem afastamento'}</strong><small>Assinado em {new Date(x.assinado_em).toLocaleString('pt-BR')} · validação {x.assinatura_hash.slice(0,12)}</small><p>{x.conteudo}</p></article>)}</RecordList>}
    {tab==='conta'&&<RecordList empty="Nenhum item assistencial lançado.">{data.conta.map(x=><article key={x.id}><strong>{x.descricao}</strong><small>{x.codigo_tuss||'Sem TUSS'} · {x.quantidade} × R$ {Number(x.valor_unitario).toFixed(2)} · {x.status}</small></article>)}</RecordList>}
    {tab==='timeline'&&<RecordList empty="Nenhuma mudança de status registrada.">{data.status.map(x=><article key={x.id}><strong>{x.status_anterior||'INÍCIO'} → {x.status_novo}</strong><small>{new Date(x.created_at).toLocaleString('pt-BR')}</small></article>)}</RecordList>}
  </section>;
}
function RecordList({children,empty}){return <div className="support-list">{children?.length?children:<p>{empty}</p>}</div>}
