import { useEffect,useState } from 'react';
import Icon from './Icon';
import { loadClinicalQueue,registerClinicalEvolution } from '../lib/hisApi';
import { validateClinicalEvolution } from '../lib/clinicalRules';

const empty={atendimento_id:'',subjetivo:'',objetivo:'',avaliacao:'',plano:'',cid10:'',desfecho:'PERMANECE',finalizar:false};
export default function ClinicalModule({onPatientSelected}){
  const[queue,setQueue]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''),[success,setSuccess]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  async function reload(){setLoading(true);try{setQueue(await loadClinicalQueue());setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{reload();},[]);
  function select(item){setForm({...empty,atendimento_id:item.id});setSuccess('');onPatientSelected?.(item.pacientes);}
  async function submit(event){event.preventDefault();const errors=validateClinicalEvolution(form);if(errors.length){setError(errors.join(' '));return;}setSaving(true);try{await registerClinicalEvolution(form);setSuccess(form.finalizar?'Atendimento finalizado com segurança.':'Evolução registrada no prontuário.');setForm(empty);setError('');await reload();}catch(e){setError(e.message);}finally{setSaving(false);}}
  return <section className="module-workspace clinical-module"><header><div><span className="eyebrow">ESTAÇÃO CLÍNICA</span><h3>Atendimento em andamento</h3><p>Evolução estruturada no padrão SOAP e desfecho assistencial auditável.</p></div><span className="tag blue">{queue.length} em atendimento</span></header>{error&&<p className="module-error">{error}</p>}{success&&<p className="module-success">{success}</p>}<div className="clinical-layout"><aside className="clinical-queue"><h4>Fila clínica</h4>{loading?<p>Carregando...</p>:queue.length?queue.map(item=>{const triage=item.triagens?.[0];return <button key={item.id} className={form.atendimento_id===item.id?'selected':''} onClick={()=>select(item)}><span className="mini-avatar">{item.pacientes.nome.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><div><strong>{item.pacientes.nome}</strong><small>{triage?.queixa_principal||'Sem queixa registrada'}</small></div>{triage&&<span className={`risk-dot ${triage.classificacao.toLowerCase()}`}>{triage.classificacao}</span>}<Icon name="chevron" size={14}/></button>}):<div className="compact-empty">Nenhum paciente em atendimento.</div>}</aside><form className="clinical-form" onSubmit={submit}><div className="clinical-summary"><strong>{form.atendimento_id?'Paciente selecionado':'Selecione um paciente da fila'}</strong><small>O registro será associado ao atendimento e ao profissional autenticado.</small></div>{[['subjetivo','S · Subjetivo','Relato, sintomas e história do paciente'],['objetivo','O · Objetivo','Exame físico, sinais e achados'],['avaliacao','A · Avaliação','Hipóteses e impressão diagnóstica'],['plano','P · Plano','Condutas, exames, medicamentos e orientações']].map(([field,label,placeholder])=><label key={field}>{label}<textarea disabled={!form.atendimento_id} required placeholder={placeholder} value={form[field]} onChange={e=>setForm({...form,[field]:e.target.value})}/></label>)}<div className="clinical-outcome"><label>CID-10<input disabled={!form.atendimento_id} placeholder="Ex.: R10.4" value={form.cid10} onChange={e=>setForm({...form,cid10:e.target.value.toUpperCase()})}/></label><label>Desfecho<select disabled={!form.atendimento_id} value={form.desfecho} onChange={e=>setForm({...form,desfecho:e.target.value})}><option value="PERMANECE">Permanece em atendimento</option><option value="ALTA">Alta</option><option value="INTERNACAO">Internação</option><option value="TRANSFERENCIA">Transferência</option></select></label><label className="finish-check"><input type="checkbox" disabled={!form.atendimento_id} checked={form.finalizar} onChange={e=>setForm({...form,finalizar:e.target.checked})}/> Finalizar atendimento após salvar</label></div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setForm(empty)}>Limpar</button><button className="primary" disabled={saving||!form.atendimento_id}>{saving?'Salvando...':'Registrar evolução'}</button></div></form></div></section>;
}
