import { useEffect, useState } from 'react';
import Icon from './Icon';
import { advanceReception, createPatient, createReception, loadReceptionQueue } from '../lib/hisApi';

const nextStatus = { AGENDADO: 'CHEGOU', CHEGOU: 'TRIAGEM', TRIAGEM: 'EM_ATENDIMENTO', EM_ATENDIMENTO: 'FINALIZADO' };
const actionLabel = { AGENDADO: 'Confirmar chegada', CHEGOU: 'Enviar à triagem', TRIAGEM: 'Iniciar atendimento', EM_ATENDIMENTO: 'Finalizar' };

export default function ReceptionModule({ onPatientSelected }) {
  const [queue, setQueue] = useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({ nome:'',cpf:'',data_nascimento:'',tipo:'CONSULTA',prioridade:'NORMAL',observacoes:'' });
  async function reload(){setLoading(true);try{setQueue(await loadReceptionQueue());setError('');}catch(err){setError(err.message);}finally{setLoading(false);}}
  useEffect(()=>{reload();},[]);
  async function submit(event){event.preventDefault();setSaving(true);setError('');try{const patient=await createPatient({nome:form.nome.trim(),cpf:form.cpf.replace(/\D/g,'')||null,data_nascimento:form.data_nascimento||null});await createReception({paciente_id:patient.id,tipo:form.tipo,prioridade:form.prioridade,status:'CHEGOU',data_chegada:new Date().toISOString(),observacoes:form.observacoes||null});setForm({nome:'',cpf:'',data_nascimento:'',tipo:'CONSULTA',prioridade:'NORMAL',observacoes:''});setShowForm(false);await reload();}catch(err){setError(err.message);}finally{setSaving(false);}}
  async function advance(item){try{await advanceReception(item.id,nextStatus[item.status]);await reload();}catch(err){setError(err.message);}}
  return <section className="module-workspace reception-module"><header><div><span className="eyebrow">RECEPÇÃO EM TEMPO REAL</span><h3>Chegadas e encaminhamentos</h3><p>Cadastre o paciente, registre a chegada e acompanhe até o atendimento.</p></div><button className="primary" onClick={()=>setShowForm(!showForm)}><Icon name="plus" size={14}/>{showForm?'Fechar formulário':'Nova chegada'}</button></header>{error&&<p className="module-error">{error}</p>}{showForm&&<form className="reception-form" onSubmit={submit}><label>Nome completo<input required minLength="3" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label>CPF<input inputMode="numeric" maxLength="14" value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})}/></label><label>Nascimento<input type="date" value={form.data_nascimento} onChange={e=>setForm({...form,data_nascimento:e.target.value})}/></label><label>Atendimento<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>CONSULTA</option><option>URGENCIA</option><option>EXAME</option><option>INTERNACAO</option></select></label><label>Prioridade<select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}><option>NORMAL</option><option>PRIORITARIO</option><option>URGENTE</option></select></label><label className="wide">Observações<input maxLength="500" value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label><div className="form-actions wide"><button type="button" className="secondary" onClick={()=>setShowForm(false)}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando...':'Cadastrar chegada'}</button></div></form>}<div className="queue-toolbar"><strong>{queue.length} pacientes na fila</strong><button onClick={reload}>Atualizar</button></div>{loading?<div className="empty-queue">Carregando fila...</div>:queue.length===0?<div className="empty-queue"><Icon name="calendar" size={24}/><div><strong>Nenhuma chegada pendente</strong><p>Novos atendimentos aparecerão aqui em tempo real.</p></div></div>:<div className="queue-list">{queue.map(item=><article key={item.id}><button className="patient-link" onClick={()=>onPatientSelected?.(item.pacientes)}><span className="mini-avatar">{item.pacientes?.nome?.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><div><strong>{item.pacientes?.nome}</strong><small>CPF {item.pacientes?.cpf||'não informado'} · {item.tipo}</small></div></button><span className={`priority ${item.prioridade.toLowerCase()}`}>{item.prioridade}</span><span className="queue-status">{item.status.replaceAll('_',' ')}</span><time>{new Date(item.data_chegada).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</time><button className="secondary" onClick={()=>advance(item)}>{actionLabel[item.status]} <Icon name="chevron" size={12}/></button></article>)}</div>}</section>;
}
