import { useEffect,useState } from 'react';
import Icon from './Icon';
import { advanceReception,loadTriageQueue,registerTriage } from '../lib/hisApi';
import { RISK_LEVELS,validateTriage } from '../lib/triageRules';

const empty={atendimento_id:'',classificacao:'VERDE',queixa_principal:'',pressao_sistolica:'',pressao_diastolica:'',frequencia_cardiaca:'',saturacao:'',temperatura:'',escala_dor:'',observacoes:''};
export default function TriageModule({onPatientSelected}){
 const[queue,setQueue]=useState([]),[form,setForm]=useState(empty),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function reload(){setLoading(true);try{setQueue(await loadTriageQueue());setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{reload();},[]);
 function select(item){setForm({...empty,atendimento_id:item.id});onPatientSelected?.(item.pacientes);}
 async function submit(e){e.preventDefault();const errors=validateTriage(form);if(errors.length){setError(errors.join(' '));return;}setSaving(true);try{await registerTriage(form);setForm(empty);await reload();}catch(err){setError(err.message);}finally{setSaving(false);}}
 async function startCare(item,event){event.stopPropagation();try{await advanceReception(item.id,'EM_ATENDIMENTO');await reload();}catch(err){setError(err.message);}}
 return <section className="module-workspace triage-module"><header><div><span className="eyebrow">PRONTO ATENDIMENTO</span><h3>Classificação de risco</h3><p>A decisão clínica permanece sob responsabilidade do profissional habilitado.</p></div><span className="tag blue">{queue.filter(x=>!x.triagens?.length).length} aguardando</span></header>{error&&<p className="module-error">{error}</p>}<div className="triage-layout"><div className="triage-queue"><h4>Fila para classificação</h4>{loading?<p>Carregando...</p>:queue.map(item=><button key={item.id} className={form.atendimento_id===item.id?'selected':''} onClick={()=>select(item)}><span className="mini-avatar">{item.pacientes.nome.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><div><strong>{item.pacientes.nome}</strong><small>Chegada {new Date(item.data_chegada).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div>{item.triagens?.[0]?<><span className={`risk-dot ${item.triagens[0].classificacao.toLowerCase()}`}>{item.triagens[0].classificacao}</span><span className="start-care" onClick={event=>startCare(item,event)}>Atender</span></>:<Icon name="chevron" size={15}/>}</button>)}</div><form className="triage-form" onSubmit={submit}><h4>Registro clínico da triagem</h4><label className="wide">Queixa principal<textarea required value={form.queixa_principal} onChange={e=>setForm({...form,queixa_principal:e.target.value})}/></label><label>Classificação<select value={form.classificacao} onChange={e=>setForm({...form,classificacao:e.target.value})}>{RISK_LEVELS.map(level=><option key={level}>{level}</option>)}</select></label><label>Pressão arterial<div className="inline-inputs"><input type="number" placeholder="Sistólica" value={form.pressao_sistolica} onChange={e=>setForm({...form,pressao_sistolica:e.target.value})}/><input type="number" placeholder="Diastólica" value={form.pressao_diastolica} onChange={e=>setForm({...form,pressao_diastolica:e.target.value})}/></div></label><label>Frequência cardíaca<input type="number" value={form.frequencia_cardiaca} onChange={e=>setForm({...form,frequencia_cardiaca:e.target.value})}/></label><label>Saturação %<input type="number" value={form.saturacao} onChange={e=>setForm({...form,saturacao:e.target.value})}/></label><label>Temperatura °C<input type="number" step="0.1" value={form.temperatura} onChange={e=>setForm({...form,temperatura:e.target.value})}/></label><label>Dor (0–10)<input type="number" min="0" max="10" value={form.escala_dor} onChange={e=>setForm({...form,escala_dor:e.target.value})}/></label><label className="wide">Observações<textarea value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label><div className="form-actions wide"><button className="primary" disabled={saving||!form.atendimento_id}>{saving?'Registrando...':'Concluir classificação'}</button></div></form></div></section>;
}
